language: generic

services:
  - docker

cache:
  directories:
    - $HOME/.ccache

git:
  quiet: true

env:
  global:
    - ROS_REPO=ros
    - CCACHE_DIR=$HOME/.ccache
    - AFTER_SCRIPT='./test_haros_report.sh'
  matrix:
    - ROS_DISTRO="kinetic"  DOWNSTREAM_WORKSPACE="github:ipa-jfh/haros_catkin_test#master"
    - ROS_DISTRO="melodic"  DOWNSTREAM_WORKSPACE="github:ipa-jfh/haros_catkin_test#master"

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master

script:
  - .industrial_ci/travis.sh
